[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = [
  'npm ci',
  'cd server && npm ci'
]

[phases.build]
cmds = [
  'npm run build',
  'cd server && npm run build'
]

[start]
cmd = 'cd server && npm start'